#!/usr/bin/env python3
"""Compose AGENTS.md from agents/ fragments for prompt-prefix caching.

Design goals (xAI / Grok auto prompt-cache):
  - Stable byte-identical output when inputs are unchanged (prefix cache hits).
  - Front-load durable rules; keep volatile plans/tasks out of the default set.
  - Deterministic file order; no timestamps or git versions in the body.
  - Atomic writes; skip rewrite when content is identical (stable mtime).

Grok loads root AGENTS.md into the system prompt at session start. That is the
cacheable prefix for the whole session — do not stuff tasks/plans in here
unless you deliberately want them on every turn.

Typical usage:
  agentsmd_build.py                  # --preset=core (stable rules)
  agentsmd_build.py --preset=full    # core + nvim/secrets, no plans/tasks
  agentsmd_build.py --preset=all     # everything under agents/ (debug/export)
  agentsmd_build.py tasks/foo.md     # core + one task for a focused session

Coupled with scripts/gen/gen-agentsmd.py:
  When you change this file, update gen-agentsmd.py if its copy/install behavior
  or shared version identity needs to stay aligned (and vice versa). Shared
  --version is the last git commit that touched either path (see get_version).
"""

from __future__ import annotations

import argparse
import os
import re
import subprocess
import sys
import tempfile
from pathlib import Path
from typing import Iterable, List, Optional, Sequence, Set

PROJECT_ROOT = Path(__file__).resolve().parent
AGENTS_DIR = PROJECT_ROOT / "agents"

# Durable rules only. Order is intentional for prefix caching:
# project → general rules → security → scripting → comments → docs → presentation.
# Language guides (agents/languages/) are on-demand — not in core (token cost).
CORE_PREPEND: List[str] = [
    "project.md",
    "general.md",
    "security.md",
    "scripting.md",
    "comments.md",
    "documentation.md",
    "ansi-colors.md",
    "markdown.md",
]
CORE_APPEND: List[str] = []

# Included by --preset=full (still stable; not session-volatile).
FULL_EXTRAS: List[str] = [
    "nvim.md",
    "secrets.md",
]

# Never auto-pulled by core/full. Must be named on the CLI or via --preset=all.
# languages/ is durable but large — pull with agentsmd_build.py languages/foo.md
VOLATILE_PREFIXES: tuple[str, ...] = (
    "plans/",
    "tasks/",
)

# Optional README — large, partly duplicates project.md; only with --readme or all.
README_REL = "../README.md"

PRESETS = ("core", "full", "all")

ANSI_RESET = "\x1b[0m"
ANSI_YELLOW = "\x1b[33m"
ANSI_BLUE = "\x1b[34m"
ANSI_GREEN = "\x1b[32m"
ANSI_RED = "\x1b[31m"
ANSI_DIM = "\x1b[2m"

HEADER = (
    "<!-- Generated by agentsmd_build.py — do not edit by hand.\n"
    "     Stable core rules for prompt-prefix caching. Task/plan docs stay in\n"
    "     agents/tasks/ and agents/plans/ and should be read on demand. -->\n"
    "\n")


def should_color(mode: str) -> bool:
    if mode == "always":
        return True
    if mode == "never":
        return False
    return sys.stdout.isatty() or sys.stderr.isatty()


def colorize(text: str, code: str, enabled: bool) -> str:
    if not enabled:
        return text
    return f"{code}{text}{ANSI_RESET}"


def warn(message: str,
         path: Optional[str] = None,
         *,
         color_mode: str = "auto") -> None:
    enabled = should_color(color_mode)
    if path:
        line = f"{colorize(message, ANSI_YELLOW, enabled)} {colorize(path, ANSI_BLUE, enabled)}"
    else:
        line = colorize(message, ANSI_YELLOW, enabled)
    print(line, file=sys.stderr, flush=True)


def info(message: str, *, color_mode: str = "auto") -> None:
    print(
        colorize(message, ANSI_DIM, should_color(color_mode)),
        file=sys.stderr,
        flush=True,
    )


def bump_headings(text: str) -> str:
    """Shift ATX headings one level deeper so fragment H1s become H2 under the file title."""
    result = []
    in_code = False
    fence = ""
    for line in text.splitlines(keepends=False):
        stripped = line.lstrip()
        if stripped.startswith(("```", "~~~")):
            if not in_code:
                in_code = True
                fence = stripped[:3]
            elif stripped.startswith(fence):
                in_code = False
            result.append(line)
            continue
        if not in_code:
            m = re.match(r"^(\s*)(#{1,6})(.*)$", line)
            if m:
                indent, hashes, rest = m.groups()
                if len(hashes) < 6:
                    result.append(indent + "#" + hashes + rest)
                    continue
        result.append(line)
    return "\n".join(result) + ("\n" if text.endswith("\n") else "")


# Paths that share one version identity with gen-agentsmd (relative to shellrc root).
_VERSIONED_PATHS: tuple[str, ...] = (
    "agentsmd_build.py",
    "scripts/gen/gen-agentsmd.py",
)


def get_version() -> str:
    """Last git commit that touched this file or scripts/gen/gen-agentsmd.py.

    Keep in sync with get_version() in gen-agentsmd.py. Appends -dirty if either
    path has uncommitted changes. Falls back to \"unknown\" without git.
    """
    try:
        res = subprocess.run(
            [
                "git",
                "-C",
                str(PROJECT_ROOT),
                "log",
                "-1",
                "--format=%h",
                "--",
                *_VERSIONED_PATHS,
            ],
            capture_output=True,
            text=True,
            timeout=2,
        )
        if res.returncode != 0:
            return "unknown"
        v = res.stdout.strip()
        if not v:
            return "unknown"
        dirty = subprocess.run(
            [
                "git",
                "-C",
                str(PROJECT_ROOT),
                "status",
                "--porcelain",
                "--",
                *_VERSIONED_PATHS,
            ],
            capture_output=True,
            text=True,
            timeout=2,
        )
        if dirty.returncode == 0 and dirty.stdout.strip():
            v = f"{v}-dirty"
        return v
    except Exception:
        return "unknown"


def is_volatile(rel: str) -> bool:
    norm = rel.replace("\\", "/")
    return any(norm == p.rstrip("/") or norm.startswith(p)
               for p in VOLATILE_PREFIXES)


def resolve_under_agents(agents: Path, arg: str) -> Optional[Path]:
    clean = arg
    for prefix in ("agents/", "agents\\"):
        if clean.startswith(prefix):
            clean = clean[len(prefix):]
            break
    p = (agents / clean).resolve()
    try:
        if p.is_relative_to(agents.resolve()) and p.exists():
            return p
    except (ValueError, OSError):
        return None
    return None


def rel_posix(agents: Path, path: Path) -> str:
    return str(path.relative_to(agents)).replace(os.sep, "/")


def add_unique(result: List[str], seen: Set[str], rel: str) -> None:
    if rel not in seen:
        result.append(rel)
        seen.add(rel)


def existing_rel(agents: Path, rel: str) -> bool:
    if rel.startswith("../"):
        return (agents / rel).resolve().is_file()
    return (agents / rel).is_file()


def collect_files(
    agents: Path,
    preset: Optional[str],
    paths: Sequence[str],
    *,
    include_readme: bool,
    color_mode: str,
) -> List[str]:
    result: List[str] = []
    seen: Set[str] = set()

    if include_readme or preset == "all":
        if existing_rel(agents, README_REL):
            add_unique(result, seen, README_REL)
        elif include_readme:
            warn("README not found at",
                 str((agents / README_REL).resolve()),
                 color_mode=color_mode)

    for rel in CORE_PREPEND:
        if existing_rel(agents, rel):
            add_unique(result, seen, rel)
        else:
            warn("Core file missing under agents/:",
                 rel,
                 color_mode=color_mode)

    extras: List[str] = []
    if preset == "full":
        extras.extend(FULL_EXTRAS)
    elif preset == "all":
        for md in sorted(agents.rglob("*.md")):
            rel = rel_posix(agents, md)
            extras.append(rel)

    for arg in paths:
        target = resolve_under_agents(agents, arg)
        if not target:
            warn("Path not found under `agents/`:", arg, color_mode=color_mode)
            continue
        if target.is_file():
            extras.append(rel_posix(agents, target))
        elif target.is_dir():
            for md in sorted(target.rglob("*.md")):
                extras.append(rel_posix(agents, md))

    # Stable extras: non-volatile first (sorted), then volatile (sorted).
    # Volatile last so core/rules prefix stays a stable cacheable head when
    # you pin a task for one session.
    stable_extras = sorted(
        {r
         for r in extras if r not in seen and not is_volatile(r)})
    volatile_extras = sorted(
        {r
         for r in extras if r not in seen and is_volatile(r)})

    for rel in stable_extras:
        if rel in CORE_APPEND:
            continue
        if existing_rel(agents, rel):
            add_unique(result, seen, rel)

    for rel in CORE_APPEND:
        if existing_rel(agents, rel):
            add_unique(result, seen, rel)
        else:
            warn("Appended file not found under agents/",
                 rel,
                 color_mode=color_mode)

    for rel in volatile_extras:
        if existing_rel(agents, rel):
            add_unique(result, seen, rel)

    return result


def compose(agents: Path, rels: Sequence[str]) -> str:
    parts: List[str] = [HEADER.rstrip("\n"), ""]
    for rel in rels:
        raw_path = (agents / rel)
        content = raw_path.read_text(encoding="utf-8").rstrip()
        bumped = bump_headings(content)
        # Fixed section chrome — do not include mtimes, sizes, or hashes here
        # (they would bust the system-prompt cache every rebuild).
        parts.append("---")
        parts.append(f"# {rel}")
        parts.append("---")
        parts.append("")
        parts.append(bumped)
        parts.append("")
    return "\n".join(parts).rstrip() + "\n"


def approx_tokens(text: str) -> int:
    # Rough chars/4 heuristic for planning only — not a real tokenizer.
    return max(1, len(text) // 4) if text else 0


def write_atomic(target: Path, content: str) -> bool:
    """Write atomically. Returns True if the file content changed."""
    target.parent.mkdir(parents=True, exist_ok=True)
    if target.is_file():
        try:
            if target.read_text(encoding="utf-8") == content:
                return False
        except OSError:
            pass

    fd, tmp_name = tempfile.mkstemp(
        prefix=".AGENTS.",
        suffix=".tmp",
        dir=str(target.parent),
    )
    tmp_path = Path(tmp_name)
    try:
        with os.fdopen(fd, "w", encoding="utf-8", newline="\n") as fh:
            fh.write(content)
            fh.flush()
            os.fsync(fh.fileno())
        os.replace(tmp_path, target)
    except Exception:
        try:
            tmp_path.unlink(missing_ok=True)
        except OSError:
            pass
        raise
    return True


def display_path(target: Path) -> str:
    try:
        return str(target.relative_to(Path.cwd().resolve()))
    except ValueError:
        return str(target)


def main(argv: Optional[Sequence[str]] = None) -> int:
    parser = argparse.ArgumentParser(
        description=
        "Compose AGENTS.md from agents/ fragments (cache-friendly).",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""Presets:
  core   Stable rules only (default). Best for prompt-prefix caching.
  full   core + nvim.md + secrets.md (still no plans/tasks/languages).
  all    Every agents/**/*.md including plans/, tasks/, languages/ (export/debug).

Examples:
  agentsmd_build.py
  agentsmd_build.py --preset=full
  agentsmd_build.py tasks/shellrc-startup_progress.md
  agentsmd_build.py languages/python.md
  agentsmd_build.py --preset=core --stdout | wc -c
  agentsmd_build.py --list --preset=all

Caching tips:
  - Prefer core/full so the system prompt is stable across sessions.
  - Pin at most one task file when you need it in-prefix for a session.
  - Read plans and language guides via tools instead of baking them in.
""",
    )
    parser.add_argument(
        "paths",
        nargs="*",
        help=
        "Extra file/dir paths relative to agents/ (appended; volatile last)",
    )
    parser.add_argument(
        "--preset",
        choices=PRESETS,
        default="core",
        help="Fragment bundle (default: core)",
    )
    parser.add_argument(
        "--readme",
        action="store_true",
        help=
        "Include ../README.md at the front (usually skip — project.md covers it)",
    )
    parser.add_argument("-o", "--output", help="Destination (relative to CWD)")
    parser.add_argument("--stdout", action="store_true", help="Emit to stdout")
    parser.add_argument(
        "--list",
        action="store_true",
        help="Print resolved fragment list and exit (no write)",
    )
    parser.add_argument(
        "--stats",
        action="store_true",
        help="Print size / approx token stats on stderr",
    )
    parser.add_argument(
        "--color",
        choices=["always", "never", "auto"],
        default="auto",
        help="Color mode",
    )
    parser.add_argument(
        "-v",
        "--version",
        action="store_true",
        help="Print version",
    )
    args = parser.parse_args(argv)

    color_mode = args.color

    if args.version:
        print(get_version())
        return 0

    if not AGENTS_DIR.is_dir():
        print(
            colorize("agents/ dir not found", ANSI_RED,
                     should_color(color_mode)),
            file=sys.stderr,
        )
        return 2

    rels = collect_files(
        AGENTS_DIR,
        args.preset,
        args.paths,
        include_readme=args.readme,
        color_mode=color_mode,
    )

    if args.list:
        for rel in rels:
            tag = " volatile" if is_volatile(rel) else ""
            print(f"{rel}{tag}")
        if args.stats:
            content = compose(AGENTS_DIR, rels)
            info(
                f"{len(rels)} files, {len(content)} bytes, ~{approx_tokens(content)} tokens",
                color_mode=color_mode,
            )
        return 0

    if not rels:
        warn("No fragments selected — refusing to write empty AGENTS.md",
             color_mode=color_mode)
        return 1

    content = compose(AGENTS_DIR, rels)

    if args.stats:
        volatile_n = sum(1 for r in rels if is_volatile(r))
        info(
            f"{len(rels)} files ({volatile_n} volatile), "
            f"{len(content)} bytes, ~{approx_tokens(content)} tokens",
            color_mode=color_mode,
        )

    if args.stdout:
        sys.stdout.write(content)
        return 0

    if args.output:
        target = (Path.cwd() / args.output).resolve()
        if target.is_dir() or str(args.output).endswith(("/", "\\")):
            target = target / "AGENTS.md"
    else:
        target = (PROJECT_ROOT / "AGENTS.md").resolve()

    try:
        changed = write_atomic(target, content)
        disp = display_path(target)
        if changed:
            print(
                colorize(f"Wrote {disp}", ANSI_GREEN,
                         should_color(color_mode)))
        else:
            print(
                colorize(f"Unchanged {disp}", ANSI_GREEN,
                         should_color(color_mode)) +
                colorize(" (cache-stable)", ANSI_DIM, should_color(color_mode))
            )
    except Exception as e:
        print(
            colorize(f"Write failed: {e}", ANSI_RED, should_color(color_mode)),
            file=sys.stderr,
        )
        return 1

    return 0


if __name__ == "__main__":
    sys.exit(main())
