#!/usr/bin/env python3
"""Project agents CLI — compose root AGENTS.md from agents/ fragments.

Seeded/refreshed by the shellrc `agents` tool. Install state lives in
agents/installed/.meta.toml (not here).

Commands: build | help | --version
"""

from __future__ import annotations

import argparse
import os
import re
import sys
import tempfile
from pathlib import Path
from typing import List, Optional, Sequence, Set, Tuple

PROJECT_ROOT = Path(__file__).resolve().parent
AGENTS_DIR = PROJECT_ROOT / "agents"
INSTALLED_DIR = AGENTS_DIR / "installed"

__version__ = '0.1.4'
# agents-tool-version: 0.1.4

CORE_INSTALLED_RELS = (
    "general.md",
    "security.md",
    "scripting.md",
    "comments.md",
    "documentation.md",
    "ansi-colors.md",
    "markdown.md",
)
FULL_EXTRAS = (
    "nvim.md",
    "secrets.md",
)
VOLATILE_PREFIXES = (
    "plans/",
    "tasks/",
)
PRESETS = ("core", "full", "all")

HEADER = (
    "<!-- Generated by agents.py — do not edit by hand.\n"
    "     Stable core rules for prompt-prefix caching. Task/plan docs stay in\n"
    "     agents/tasks/ and agents/plans/ and should be read on demand. -->\n"
    "\n"
)


def is_volatile(rel: str) -> bool:
    norm = rel.replace("\\", "/")
    return any(
        norm == p.rstrip("/") or norm.startswith(p) for p in VOLATILE_PREFIXES
    )


def bump_headings(text: str) -> str:
    result: List[str] = []
    in_code = False
    fence = ""
    for line in text.splitlines(keepends=False):
        stripped = line.lstrip()
        if stripped.startswith(("```", "~~~")):
            if not in_code:
                in_code = True
                fence = stripped[:3]
            elif stripped.startswith(fence):
                in_code = False
            result.append(line)
            continue
        if not in_code:
            m = re.match(r"^(\s*)(#{1,6})(.*)$", line)
            if m:
                indent, hashes, rest = m.groups()
                if len(hashes) < 6:
                    result.append(indent + "#" + hashes + rest)
                    continue
        result.append(line)
    return "\n".join(result) + ("\n" if text.endswith("\n") else "")


def _rel_posix(base: Path, path: Path) -> str:
    return str(path.relative_to(base)).replace(os.sep, "/")


def _label_for(path: Path) -> str:
    # Keep installed/ prefix so user overrides can follow with a distinct label
    return _rel_posix(AGENTS_DIR, path)


def _user_override_label(rel: str) -> str:
    return f"{rel} (user)"


def _resolve_under_agents(arg: str) -> Optional[Path]:
    clean = arg.replace("\\", "/")
    for prefix in ("agents/", "./agents/"):
        if clean.startswith(prefix):
            clean = clean[len(prefix) :]
            break
    cand = (AGENTS_DIR / clean).resolve()
    try:
        if cand.is_relative_to(AGENTS_DIR.resolve()) and cand.exists():
            return cand
    except (ValueError, OSError):
        pass
    if not clean.startswith("installed/"):
        cand2 = (INSTALLED_DIR / clean).resolve()
        try:
            if cand2.is_relative_to(AGENTS_DIR.resolve()) and cand2.exists():
                return cand2
        except (ValueError, OSError):
            pass
    return None


def collect_fragments(
    preset: str = "core",
    paths: Sequence[str] = (),
    *,
    include_readme: bool = False,
) -> List[Tuple[str, Path]]:
    result: List[Tuple[str, Path]] = []
    seen: Set[str] = set()
    has_installed = INSTALLED_DIR.is_dir() and any(INSTALLED_DIR.rglob("*.md"))
    installed_rels: Set[str] = set()

    def add_labeled(label: str, path: Path) -> None:
        if label not in seen and path.is_file():
            result.append((label, path))
            seen.add(label)

    def existing_managed(rel: str) -> Optional[Path]:
        p = INSTALLED_DIR / rel
        if p.is_file():
            installed_rels.add(rel)
            return p
        if has_installed:
            return None
        p2 = AGENTS_DIR / rel
        if p2.is_file() and rel != "project.md":
            return p2
        return None

    if include_readme or preset == "all":
        readme = PROJECT_ROOT / "README.md"
        if readme.is_file():
            add_labeled("../README.md", readme)

    project_md = AGENTS_DIR / "project.md"
    if project_md.is_file():
        add_labeled("project.md", project_md)

    for rel in CORE_INSTALLED_RELS:
        p = existing_managed(rel)
        if p is not None:
            add_labeled(_label_for(p.resolve()), p)

    extras: List[Path] = []
    if preset == "full":
        for rel in FULL_EXTRAS:
            p = existing_managed(rel)
            if p is not None:
                extras.append(p)
        if INSTALLED_DIR.is_dir():
            for md in sorted(INSTALLED_DIR.rglob("*.md")):
                rel = _rel_posix(INSTALLED_DIR, md)
                installed_rels.add(rel)
                if is_volatile(rel) or rel.startswith("languages/"):
                    continue
                if rel in CORE_INSTALLED_RELS or rel in FULL_EXTRAS:
                    continue
                extras.append(md)
    elif preset == "all":
        if AGENTS_DIR.is_dir():
            for md in sorted(AGENTS_DIR.rglob("*.md")):
                if not md.name.startswith("."):
                    extras.append(md)

    for arg in paths:
        target = _resolve_under_agents(arg)
        if target is None:
            print(f"warning: path not found under agents/: {arg}", file=sys.stderr)
            continue
        if target.is_file():
            extras.append(target)
        elif target.is_dir():
            for md in sorted(target.rglob("*.md")):
                if not md.name.startswith("."):
                    extras.append(md)

    stable: List[Tuple[str, Path]] = []
    volatile: List[Tuple[str, Path]] = []
    for p in extras:
        try:
            p = p.resolve()
            if not p.is_file():
                continue
            if p.parent == PROJECT_ROOT and p.name == "README.md":
                label = "../README.md"
            else:
                if not p.is_relative_to(AGENTS_DIR.resolve()):
                    continue
                rel_agents = _rel_posix(AGENTS_DIR, p)
                if (
                    has_installed
                    and not rel_agents.startswith("installed/")
                    and not is_volatile(rel_agents)
                    and rel_agents != "project.md"
                    and (INSTALLED_DIR / rel_agents).is_file()
                ):
                    installed_rels.add(rel_agents)
                    continue
                label = _label_for(p)
        except (ValueError, OSError):
            continue
        if label in seen:
            continue
        if is_volatile(label) or (
            label.startswith("installed/")
            and is_volatile(label[len("installed/") :])
        ):
            volatile.append((label, p))
        else:
            stable.append((label, p))

    for label, p in sorted(stable, key=lambda t: t[0]):
        add_labeled(label, p)

    if has_installed and INSTALLED_DIR.is_dir():
        for md in INSTALLED_DIR.rglob("*.md"):
            installed_rels.add(_rel_posix(INSTALLED_DIR, md))
        for rel in sorted(installed_rels):
            if is_volatile(rel):
                continue
            user_p = AGENTS_DIR / rel
            if not user_p.is_file():
                continue
            if preset == "core" and rel not in CORE_INSTALLED_RELS:
                continue
            if preset == "full" and rel.startswith("languages/"):
                continue
            add_labeled(_user_override_label(rel), user_p)

    for label, p in sorted(volatile, key=lambda t: t[0]):
        add_labeled(label, p)
    return result


def compose_text(fragments: Sequence[Tuple[str, Path]]) -> str:
    parts: List[str] = [HEADER.rstrip("\n"), ""]
    for label, path in fragments:
        content = path.read_text(encoding="utf-8").rstrip()
        bumped = bump_headings(content)
        parts.append("---")
        parts.append(f"# {label}")
        parts.append("---")
        parts.append("")
        parts.append(bumped)
        parts.append("")
    return "\n".join(parts).rstrip() + "\n"


def write_atomic(target: Path, content: str) -> bool:
    target.parent.mkdir(parents=True, exist_ok=True)
    if target.is_file():
        try:
            if target.read_text(encoding="utf-8") == content:
                return False
        except OSError:
            pass
    fd, tmp_name = tempfile.mkstemp(
        prefix=".AGENTS.",
        suffix=".tmp",
        dir=str(target.parent),
    )
    tmp_path = Path(tmp_name)
    try:
        with os.fdopen(fd, "w", encoding="utf-8", newline="\n") as fh:
            fh.write(content)
            fh.flush()
            os.fsync(fh.fileno())
        os.replace(tmp_path, target)
    except Exception:
        try:
            tmp_path.unlink(missing_ok=True)
        except OSError:
            pass
        raise
    return True


def cmd_build(argv: Sequence[str]) -> int:
    parser = argparse.ArgumentParser(
        prog="agents.py build",
        description="Compose AGENTS.md from agents/installed/ + user fragments.",
    )
    parser.add_argument(
        "paths",
        nargs="*",
        help="Extra file/dir paths relative to agents/ (volatile last)",
    )
    parser.add_argument(
        "--preset",
        choices=PRESETS,
        default="core",
        help="Fragment bundle (default: core)",
    )
    parser.add_argument(
        "--readme",
        action="store_true",
        help="Include ../README.md at the front",
    )
    parser.add_argument("-o", "--output", help="Destination path")
    parser.add_argument("--stdout", action="store_true", help="Emit to stdout")
    parser.add_argument(
        "--list",
        action="store_true",
        help="Print resolved fragment list and exit",
    )
    args = parser.parse_args(list(argv))

    if not AGENTS_DIR.is_dir():
        print(f"error: agents/ not found under {PROJECT_ROOT}", file=sys.stderr)
        return 2

    frags = collect_fragments(
        args.preset,
        args.paths,
        include_readme=args.readme,
    )

    if args.list:
        for label, _ in frags:
            tag = " volatile" if is_volatile(label) else ""
            print(f"{label}{tag}")
        return 0

    if not frags:
        print(
            "error: no fragments selected — refusing to write empty AGENTS.md",
            file=sys.stderr,
        )
        return 1

    content = compose_text(frags)

    if args.stdout:
        sys.stdout.write(content)
        return 0

    if args.output:
        target = Path(args.output)
        if not target.is_absolute():
            target = (Path.cwd() / target).resolve()
        if target.is_dir() or str(args.output).endswith(("/", "\\")):
            target = target / "AGENTS.md"
    else:
        target = PROJECT_ROOT / "AGENTS.md"

    try:
        changed = write_atomic(target, content)
    except OSError as exc:
        print(f"error: write failed: {exc}", file=sys.stderr)
        return 1

    try:
        disp = str(target.relative_to(Path.cwd().resolve()))
    except ValueError:
        disp = str(target)
    if changed:
        print(f"Wrote {disp}")
    else:
        print(f"Unchanged {disp} (cache-stable)")
    return 0


def usage() -> None:
    print(
        f"""agents.py {__version__} — project agents composer

Commands:
  build [paths…]     Compose root AGENTS.md (default --preset=core)
  help               This help
  --version          Print version

build options:
  --preset=core|full|all
  --readme           Include project README.md
  --stdout           Write composed text to stdout
  --list             Print fragment list only
  -o PATH            Output path (default: ./AGENTS.md)

Fragments come from agents/project.md and agents/installed/ (core order).
Pass extra paths (e.g. languages/python.md) to append. plans/ and tasks/
are volatile and sort last.

Install/update fragments with the shellrc `agents` tool — this script only
composes.
"""
    )


def main(argv: Optional[Sequence[str]] = None) -> int:
    args = list(sys.argv[1:] if argv is None else argv)
    if not args or args[0] in ("-h", "--help", "help"):
        usage()
        return 0
    if args[0] in ("--version", "-V", "version"):
        print(f"agents.py {__version__}")
        return 0
    if args[0] == "build":
        return cmd_build(args[1:])
    print(f"error: unknown command {args[0]!r} (try: build, help, --version)", file=sys.stderr)
    return 1


if __name__ == "__main__":
    raise SystemExit(main())
